---
name: cAdvisor
version: v0.1.3
slug: cadvisor
description: A container metrics exporter for Prometheus
url: https://github.com/christian-vdz/hassio-cadvisor-addon
webui: http://[HOST]:[PORT:8080]
watchdog: http://[HOST]:[PORT:8080]/healthz
init: false
docker_api: true
full_access: true
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
